import { Poppins } from "next/font/google";
import "./globals.css";
import ChatAssistant from "../components/ChatAssistant";

const poppins = Poppins({
  variable: "--font-base",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        {children}
        <ChatAssistant />
      </body>
    </html>
  );
}
