import { Poppins } from "next/font/google";
import "./globals.css";
import ChatAssistant from "../components/ChatAssistant";
import { AuthProvider } from "../context/AuthContext";
import LoginModalContainer from "../components/LoginModalContainer";
import RegisterModalContainer from "../components/RegisterModalContainer";
import VerificationModalContainer from "../components/VerificationModalContainer";

const poppins = Poppins({
  variable: "--font-base",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <AuthProvider>
          {children}
          <LoginModalContainer />
          <RegisterModalContainer />
          <VerificationModalContainer />
          <ChatAssistant />
        </AuthProvider>
      </body>
    </html>
  );
}
